### ISSUE TITLE
Can't initiate basic weather configuration

### ISSUE THREAD

**Issue by mfyz** [plouc/mozaik-ext-weather#16]
item                           | info       | notes
-------------------------------|------------|---------------------------------------------------------------------------------------------
**node** version               |            | v8.3.0
**npm** version                |            | 5.5.1
**mozaik-ext-weather** version |            | ^1.2.0
**mozaik** version             |            | 1.4.4
**mozaik-demo** version        |            | don't know - github snapshot downloaded on Dec4
**component**                  |            | don't know
**browser**                    |            | chrome safari on mac

## Expected behavior

Weather widget to appear in dashbaord.

## Actual behavior

It makes server crash with the exception: 

```
Error: Unable to find API matching id 'weather'
    at Object.clientSubscription (Bus.js:160:19)
    at WebSocket.<anonymous> (server.js:53:24)
    at emitTwo (events.js:125:13)
    at WebSocket.emit (events.js:213:7)
    at Receiver.ontext (/Users/fatih/Applications/mozaik/node_modules/ws/lib/WebSocket.js:841:10)
    at /Users/fatih/Applications/mozaik/node_modules/ws/lib/Receiver.js:536:18
    at /Users/fatih/Applications/mozaik/node_modules/ws/lib/Receiver.js:368:7
    at /Users/fatih/Applications/mozaik/node_modules/ws/lib/PerMessageDeflate.js:249:5
    at afterWrite (_stream_writable.js:438:3)
    at onwrite (_stream_writable.js:429:7)
    at InflateRaw.afterTransform (_stream_transform.js:90:3)
    at Zlib.callback (zlib.js:514:5)
```

I've tried the open weather api token in both config.js and environment.

## Steps to reproduce

Just run the server with following weather config:

````
{
    type:    'weather.weather',
    city:    'New York',
    country: 'USA',
    columns: 1, rows: 1,
    x: 1, y: 0
}
```

**Comment by mfyz** [comment]
Idiotically had syntax issue on registering the client in server.js.
